export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESSFUL = "FETCH_USER_SUCCESSFUL";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const SEND_NEW_OFFER = "SEND_NEW_OFFER";
export const SEND_NEW_OFFER_FAILED = "SEND_NEW_OFFER_FAILED";

export const FETCH_OFFERS = "FETCH_OFFERS";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_FAILED = "FETCH_OFFERS_FAILED";

export const DELETE_OFFER = "DELETE_OFFER";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAILED = "DELETE_OFFER_FAILED";

export const FETCH_OFFER_DETAILS = "FETCH_OFFER_DETAILS";
export const FETCH_OFFER_DETAILS_SUCCESS = "FETCH_OFFER_DETAILS_SUCCESS";
export const FETCH_OFFER_DETAILS_FAILED = "FETCH_OFFER_DETAILS_FAILED";
