export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESSFUL = 'FETCH_USER_SUCCESSFUL';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const SEND_NEW_OFFER = 'SEND_NEW_OFFER';
export const SEND_NEW_OFFER_FAILED = 'SEND_NEW_OFFER_FAILED';